# Generated by Django 2.2.13 on 2021-03-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ニックネーム')),
                ('golfriend_id', models.CharField(max_length=20, verbose_name='ゴルフレID')),
                ('header_image', models.ImageField(upload_to='images', verbose_name='ヘッダー画像')),
                ('thumbnail', models.ImageField(upload_to='images', verbose_name='サムネイル')),
                ('introduction', models.TextField(blank=True, max_length=100, null=True, verbose_name='自己紹介')),
            ],
        ),
    ]
