# Generated by Django 2.2.13 on 2021-04-03 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
