# Generated by Django 2.2.13 on 2021-04-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20210403_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='user_num',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
