# Generated by Django 2.2.13 on 2021-05-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_board_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardModel',
        ),
    ]
